### ISSUE TITLE
exporting images?

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#34] opened 2018-11-22 09:53 UTC
My wordpress blog has a lot of images and the exported extended rss file only has the links to existing images hosted on my wordpress blog. I would expect the tools to `curl` the images and download them, and update the links in the post to the relative image paths to downloaded images.

**Comment by jashsayani** [comment] 2018-11-22 09:53
I guess this is similar to #30

**Comment by curbengh** [comment] 2020-01-11 11:11
https://github.com/hexojs/hexo-migrator-wordpress/issues/54

**Comment by curbengh** [comment] 2020-01-11 11:50
Duplicate of #21

**Closed by curbengh** 2020-01-11 11:50 UTC
