### ISSUE TITLE
The command `hexo migrate wordpress` fails

### ISSUE THREAD

**Issue by jashsayani** [hexojs/hexo-migrator-wordpress#86] opened 2020-07-25 05:14 UTC
Error: `ERROR can not read a block mapping entry; a multiline key may not be an implicit key`

![Screen Shot 2020-07-24 at 10 12 35 PM](https://user-images.githubusercontent.com/18684/88449348-f7bb8080-cdfa-11ea-985c-cfa23a657541.png)

Sample file: https://github.com/hexojs/hexo-migrator-wordpress/issues/35#issuecomment-663810839

**Comment by curbengh** [comment] 2020-07-25 05:38
I think it's caused by `<title>Gmail gets the &quot;Undo send&quot; feature!</title>`, should be fixed in https://github.com/hexojs/hexo-migrator-wordpress/pull/67 & https://github.com/hexojs/hexo-migrator-wordpress/pull/82.

**Closed** 2020-08-02 05:31 UTC
